//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_Lichni_dnevnik.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID_record { get; set; }
        public Nullable<System.DateTime> Date_record { get; set; }
        public Nullable<int> ID_mood { get; set; }
        public string Description_record { get; set; }
        public byte[] Img_record { get; set; }
        public int ID_user { get; set; }
    
        public virtual Mood Mood { get; set; }
        public virtual User User { get; set; }
    }
}
